/**
 * Contact type for backend integration
 * Represents a contact in the user's birthday reminders list
 * Backend endpoint: POST /api/contacts, GET /api/contacts, PATCH /api/contacts/:id
 */
export interface Contact {
  id: string; // UUID, generated by client or server
  name: string; // Required: contact's name
  relation?: string; // Optional: relationship (e.g., "Friend", "Family")
  birthDate?: string; // ISO 8601 date format (YYYY-MM-DD)
  phone?: string; // Optional: phone number
  email?: string; // Optional: email address
  profileImage?: string; // Optional: base64 or image URL for contact profile picture
  commonNotes?: string; // Optional: shared bio/notes about the contact
  additionalNotes?: string[]; // Optional: array of note IDs or embedded notes
  createdAt: string; // ISO 8601 timestamp
  updatedAt: string; // ISO 8601 timestamp
  isArchived?: boolean; // Optional: soft delete flag
}

/**
 * Backend schema mapping for Contact API:
 * 
 * POST /api/contacts
 * Request: { name, relation?, birthDate?, phone?, email?, profileImage?, commonNotes? }
 * Response: Contact (full object with id, createdAt, updatedAt)
 * 
 * GET /api/contacts
 * Response: Contact[]
 * 
 * GET /api/contacts/:id
 * Response: Contact
 * 
 * PATCH /api/contacts/:id
 * Request: Partial<Contact> (any updatable field)
 * Response: Contact
 * 
 * DELETE /api/contacts/:id
 * Response: { success: boolean }
 */
